version: '3.7'
services:
  envoy:
    image: "envoyproxy/envoy:v1.10.0"
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "trace"]
    ports:
      - "8443:8443"
    volumes:
      - ./run/envoy:/etc/envoy:ro
  auth:
    image: authservice:nickrmc83
    command: ["-filter_config", "/etc/authservice/config.json"]
    ports:
      - "10004:10004"
    volumes:
      - /tmp/config/config.json:/etc/authservice/config.json:ro
