# To access the envoy proxy when using `docker-compose up`, point your browser at https://0.0.0.0:8443
version: '3.7'
services:
  envoy:
    image: "envoyproxy/envoy:v1.17.0"
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    ports:
      - "9000:9000"
    volumes:
      - ./run/envoy:/etc/envoy:ro
  auth:
    build:
      dockerfile: build/Dockerfile.build
      context: ./
    image: ${IMAGE}
    command: ["-filter_config", "/etc/authservice/config.json"]
    ports:
      - "10004:10004"
    volumes:
      - ./run/config:/etc/authservice:ro
